apiVersion: v1
# at the time of writing the app lives here:
kind: Service
metadata:
  name: package-comparator
spec:
  ports:
    - name: web-http
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: package-comparator
  type: LoadBalancer
  externalTrafficPolicy: Cluster

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: package-comparator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: package-comparator
  template:
    metadata:
      labels:
        app: package-comparator
    spec:
      containers:
        - name: package-comparator
          image: gcr.io/diamond-privreg/package-comparator:0.2.0
          env:
            - name: NEXT_PUBLIC_API_HOST # not used
              value: "package-comparator.xma12127.svc.cluster.local:3001"
          resources:
            limits:
              cpu: "1"
              memory: 300M
          ports:
            - name: web-http
              containerPort: 3000
              