apiVersion: v1
# at the time of writing the web lives here http://172.23.169.108:3000/
# and API here http://172.23.169.108:3001/message/test
kind: Service
metadata:
  name: turbo
spec:
  ports:
    - name: web-http
      port: 3000
      protocol: TCP
      targetPort: 3000
    - name: api-http
      port: 3001
      protocol: TCP
      targetPort: 3001
  selector:
    app: turbo
  type: LoadBalancer
  externalTrafficPolicy: Cluster

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: turbo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: turbo
  template:
    metadata:
      labels:
        app: turbo
    spec:
      containers:
        - name: with-docker-web
          image: gcr.io/diamond-privreg/turborepo-with-docker/with-docker-web:latest
          env:
            - name: NEXT_PUBLIC_API_HOST
              value: "turbo.xma12127.svc.cluster.local:3001"
          command: ["node"]
          args: ["apps/web/server.js"]
          resources:
            limits:
              cpu: "1"
              memory: 300M
          ports:
            - name: web-http
              containerPort: 3000
        - name: with-docker-api
          image: gcr.io/diamond-privreg/turborepo-with-docker/with-docker-api:latest
          env:
            - name: PORT
              value: "3001"
          command: ["node"]
          args: ["apps/api/dist/index.js"]
          resources:
            limits:
              cpu: "1"
              memory: 300M
          ports:
            - name: api-http
              containerPort: 3001
