apiVersion: apps/v1
kind: Deployment
metadata:
  name: with-docker-web
spec:
  selector:
    matchLabels:
      app: with-docker-web
  replicas: 1
  template:
    metadata:
      labels:
        app: with-docker-web
    spec:
      containers:
      - name: with-docker-web
        image: gcr.io/diamond-privreg/turborepo-with-docker/with-docker-web:latest
        command: ["node"]
        args: ["apps/web/server.js"]
        resources:
          limits:
            cpu: "1"
            memory: 300M
        ports:
        - containerPort: 3000
