export default [
  {
    "Number": "1",
    "Type": "nonmetal",
    "Atomic Weight": "1.008",
    "Name": "Hydrogen",
    "Symbol": "H",
    "Melting Point": "-259",
    "Boiling Point": "-253",
    "Density": "0.09",
    "Earth": "0.14",
    "Group": "1",
    "Electron Configuration": "1s1"
  },
  {
    "Number": "2",
    "Type": "noble gas",
    "Atomic Weight": "4.003",
    "Name": "Helium",
    "Symbol": "He",
    "Melting Point": "-272",
    "Boiling Point": "-269",
    "Density": "0.18",
    "Earth": "",
    "Group": "18",
    "Electron Configuration": "1s2"
  },
  {
    "Number": "3",
    "Type": "alkali metal",
    "Atomic Weight": "6.941",
    "Name": "Lithium",
    "Symbol": "Li",
    "Melting Point": "180",
    "Boiling Point": "1347",
    "Density": "0.53",
    "Earth": "",
    "Group": "1",
    "Electron Configuration": "[He] 2s1"
  },
  {
    "Number": "4",
    "Type": "alkaline earth metal",
    "Atomic Weight": "9.012",
    "Name": "Beryllium",
    "Symbol": "Be",
    "Melting Point": "1278",
    "Boiling Point": "2970",
    "Density": "1.85",
    "Earth": "",
    "Group": "2",
    "Electron Configuration": "[He] 2s2"
  },
  {
    "Number": "5",
    "Type": "metalloid",
    "Atomic Weight": "10.811",
    "Name": "Boron",
    "Symbol": "B",
    "Melting Point": "2300",
    "Boiling Point": "2550",
    "Density": "2.34",
    "Earth": "",
    "Group": "13",
    "Electron Configuration": "[He] 2s2 2p1"
  },
  {
    "Number": "6",
    "Type": "nonmetal",
    "Atomic Weight": "12.011",
    "Name": "Carbon",
    "Symbol": "C",
    "Melting Point": "3500",
    "Boiling Point": "4827",
    "Density": "2.26",
    "Earth": "0.09",
    "Group": "14",
    "Electron Configuration": "[He] 2s2 2p2"
  },
  {
    "Number": "7",
    "Type": "nonmetal",
    "Atomic Weight": "14.007",
    "Name": "Nitrogen",
    "Symbol": "N",
    "Melting Point": "-210",
    "Boiling Point": "-196",
    "Density": "1.25",
    "Earth": "",
    "Group": "15",
    "Electron Configuration": "[He] 2s2 2p3"
  },
  {
    "Number": "8",
    "Type": "nonmetal",
    "Atomic Weight": "15.999",
    "Name": "Oxygen",
    "Symbol": "O",
    "Melting Point": "-218",
    "Boiling Point": "-183",
    "Density": "1.43",
    "Earth": "46.71",
    "Group": "16",
    "Electron Configuration": "[He] 2s2 2p4"
  },
  {
    "Number": "9",
    "Type": "halogen",
    "Atomic Weight": "18.998",
    "Name": "Fluorine",
    "Symbol": "F",
    "Melting Point": "-220",
    "Boiling Point": "-188",
    "Density": "1.7",
    "Earth": "0.03",
    "Group": "17",
    "Electron Configuration": "[He] 2s2 2p5"
  },
  {
    "Number": "10",
    "Type": "noble gas",
    "Atomic Weight": "20.18",
    "Name": "Neon",
    "Symbol": "Ne",
    "Melting Point": "-249",
    "Boiling Point": "-246",
    "Density": "0.9",
    "Earth": "",
    "Group": "18",
    "Electron Configuration": "[He] 2s2 2p6"
  },
  {
    "Number": "11",
    "Type": "alkali metal",
    "Atomic Weight": "22.99",
    "Name": "Sodium",
    "Symbol": "Na",
    "Melting Point": "98",
    "Boiling Point": "883",
    "Density": "0.97",
    "Earth": "2.75",
    "Group": "1",
    "Electron Configuration": "[Ne] 3s1"
  },
  {
    "Number": "12",
    "Type": "alkaline earth metal",
    "Atomic Weight": "24.305",
    "Name": "Magnesium",
    "Symbol": "Mg",
    "Melting Point": "639",
    "Boiling Point": "1090",
    "Density": "1.74",
    "Earth": "2.08",
    "Group": "2",
    "Electron Configuration": "[Ne] 3s2"
  },
  {
    "Number": "13",
    "Type": "post transition metal",
    "Atomic Weight": "26.982",
    "Name": "Aluminum",
    "Symbol": "Al",
    "Melting Point": "660",
    "Boiling Point": "2467",
    "Density": "2.7",
    "Earth": "8.07",
    "Group": "13",
    "Electron Configuration": "[Ne] 3s2 3p1"
  },
  {
    "Number": "14",
    "Type": "metalloid",
    "Atomic Weight": "28.086",
    "Name": "Silicon",
    "Symbol": "Si",
    "Melting Point": "1410",
    "Boiling Point": "2355",
    "Density": "2.33",
    "Earth": "27.69",
    "Group": "14",
    "Electron Configuration": "[Ne] 3s2 3p2"
  },
  {
    "Number": "15",
    "Type": "nonmetal",
    "Atomic Weight": "30.974",
    "Name": "Phosphorus",
    "Symbol": "P",
    "Melting Point": "44",
    "Boiling Point": "280",
    "Density": "1.82",
    "Earth": "0.13",
    "Group": "15",
    "Electron Configuration": "[Ne] 3s2 3p3"
  },
  {
    "Number": "16",
    "Type": "nonmetal",
    "Atomic Weight": "32.065",
    "Name": "Sulfur",
    "Symbol": "S",
    "Melting Point": "113",
    "Boiling Point": "445",
    "Density": "2.07",
    "Earth": "0.05",
    "Group": "16",
    "Electron Configuration": "[Ne] 3s2 3p4"
  },
  {
    "Number": "17",
    "Type": "halogen",
    "Atomic Weight": "35.453",
    "Name": "Chlorine",
    "Symbol": "Cl",
    "Melting Point": "-101",
    "Boiling Point": "-35",
    "Density": "3.21",
    "Earth": "0.05",
    "Group": "17",
    "Electron Configuration": "[Ne] 3s2 3p5"
  },
  {
    "Number": "18",
    "Type": "noble gas",
    "Atomic Weight": "39.948",
    "Name": "Argon",
    "Symbol": "Ar",
    "Melting Point": "-189",
    "Boiling Point": "-186",
    "Density": "1.78",
    "Earth": "",
    "Group": "18",
    "Electron Configuration": "[Ne] 3s2 3p6"
  },
  {
    "Number": "19",
    "Type": "alkali metal",
    "Atomic Weight": "39.098",
    "Name": "Potassium",
    "Symbol": "K",
    "Melting Point": "64",
    "Boiling Point": "774",
    "Density": "0.86",
    "Earth": "2.58",
    "Group": "1",
    "Electron Configuration": "[Ar] 4s1"
  },
  {
    "Number": "20",
    "Type": "alkaline earth metal",
    "Atomic Weight": "40.078",
    "Name": "Calcium",
    "Symbol": "Ca",
    "Melting Point": "839",
    "Boiling Point": "1484",
    "Density": "1.55",
    "Earth": "3.65",
    "Group": "2",
    "Electron Configuration": "[Ar] 4s2"
  },
  {
    "Number": "21",
    "Type": "transition metal",
    "Atomic Weight": "44.956",
    "Name": "Scandium",
    "Symbol": "Sc",
    "Melting Point": "1539",
    "Boiling Point": "2832",
    "Density": "2.99",
    "Earth": "",
    "Group": "3",
    "Electron Configuration": "[Ar] 3d1 4s2"
  },
  {
    "Number": "22",
    "Type": "transition metal",
    "Atomic Weight": "47.867",
    "Name": "Titanium",
    "Symbol": "Ti",
    "Melting Point": "1660",
    "Boiling Point": "3287",
    "Density": "4.54",
    "Earth": "0.62",
    "Group": "4",
    "Electron Configuration": "[Ar] 3d2 4s2"
  },
  {
    "Number": "23",
    "Type": "transition metal",
    "Atomic Weight": "50.942",
    "Name": "Vanadium",
    "Symbol": "V",
    "Melting Point": "1890",
    "Boiling Point": "3380",
    "Density": "6.11",
    "Earth": "",
    "Group": "5",
    "Electron Configuration": "[Ar] 3d3 4s2"
  },
  {
    "Number": "24",
    "Type": "transition metal",
    "Atomic Weight": "51.996",
    "Name": "Chromium",
    "Symbol": "Cr",
    "Melting Point": "1857",
    "Boiling Point": "2672",
    "Density": "7.19",
    "Earth": "0.04",
    "Group": "6",
    "Electron Configuration": "[Ar] 3d5 4s1"
  },
  {
    "Number": "25",
    "Type": "transition metal",
    "Atomic Weight": "54.938",
    "Name": "Manganese",
    "Symbol": "Mn",
    "Melting Point": "1245",
    "Boiling Point": "1962",
    "Density": "7.43",
    "Earth": "0.09",
    "Group": "7",
    "Electron Configuration": "[Ar] 3d5 4s2"
  },
  {
    "Number": "26",
    "Type": "transition metal",
    "Atomic Weight": "55.845",
    "Name": "Iron",
    "Symbol": "Fe",
    "Melting Point": "1535",
    "Boiling Point": "2750",
    "Density": "7.87",
    "Earth": "5.05",
    "Group": "8",
    "Electron Configuration": "[Ar] 3d6 4s2"
  },
  {
    "Number": "27",
    "Type": "transition metal",
    "Atomic Weight": "58.933",
    "Name": "Cobalt",
    "Symbol": "Co",
    "Melting Point": "1495",
    "Boiling Point": "2870",
    "Density": "8.9",
    "Earth": "",
    "Group": "9",
    "Electron Configuration": "[Ar] 3d7 4s2"
  },
  {
    "Number": "28",
    "Type": "transition metal",
    "Atomic Weight": "58.693",
    "Name": "Nickel",
    "Symbol": "Ni",
    "Melting Point": "1453",
    "Boiling Point": "2732",
    "Density": "8.9",
    "Earth": "0.02",
    "Group": "10",
    "Electron Configuration": "[Ar] 3d8 4s2"
  },
  {
    "Number": "29",
    "Type": "transition metal",
    "Atomic Weight": "63.546",
    "Name": "Copper",
    "Symbol": "Cu",
    "Melting Point": "1083",
    "Boiling Point": "2567",
    "Density": "8.96",
    "Earth": "",
    "Group": "11",
    "Electron Configuration": "[Ar] 3d10 4s1"
  },
  {
    "Number": "30",
    "Type": "transition metal",
    "Atomic Weight": "65.39",
    "Name": "Zinc",
    "Symbol": "Zn",
    "Melting Point": "420",
    "Boiling Point": "907",
    "Density": "7.13",
    "Earth": "",
    "Group": "12",
    "Electron Configuration": "[Ar] 3d10 4s2"
  },
  {
    "Number": "31",
    "Type": "post transition metal",
    "Atomic Weight": "69.723",
    "Name": "Gallium",
    "Symbol": "Ga",
    "Melting Point": "30",
    "Boiling Point": "2403",
    "Density": "5.91",
    "Earth": "",
    "Group": "13",
    "Electron Configuration": "[Ar] 3d10 4s2 4p1"
  },
  {
    "Number": "32",
    "Type": "metalloid",
    "Atomic Weight": "72.64",
    "Name": "Germanium",
    "Symbol": "Ge",
    "Melting Point": "937",
    "Boiling Point": "2830",
    "Density": "5.32",
    "Earth": "",
    "Group": "14",
    "Electron Configuration": "[Ar] 3d10 4s2 4p2"
  },
  {
    "Number": "33",
    "Type": "metalloid",
    "Atomic Weight": "74.922",
    "Name": "Arsenic",
    "Symbol": "As",
    "Melting Point": "81",
    "Boiling Point": "613",
    "Density": "5.72",
    "Earth": "",
    "Group": "15",
    "Electron Configuration": "[Ar] 3d10 4s2 4p3"
  },
  {
    "Number": "34",
    "Type": "nonmetal",
    "Atomic Weight": "78.96",
    "Name": "Selenium",
    "Symbol": "Se",
    "Melting Point": "217",
    "Boiling Point": "685",
    "Density": "4.79",
    "Earth": "",
    "Group": "16",
    "Electron Configuration": "[Ar] 3d10 4s2 4p4"
  },
  {
    "Number": "35",
    "Type": "halogen",
    "Atomic Weight": "79.904",
    "Name": "Bromine",
    "Symbol": "Br",
    "Melting Point": "-7",
    "Boiling Point": "59",
    "Density": "3.12",
    "Earth": "",
    "Group": "17",
    "Electron Configuration": "[Ar] 3d10 4s2 4p5"
  },
  {
    "Number": "36",
    "Type": "noble gas",
    "Atomic Weight": "83.8",
    "Name": "Krypton",
    "Symbol": "Kr",
    "Melting Point": "-157",
    "Boiling Point": "-153",
    "Density": "3.75",
    "Earth": "",
    "Group": "18",
    "Electron Configuration": "[Ar] 3d10 4s2 4p6"
  },
  {
    "Number": "37",
    "Type": "alkali metal",
    "Atomic Weight": "85.468",
    "Name": "Rubidium",
    "Symbol": "Rb",
    "Melting Point": "39",
    "Boiling Point": "688",
    "Density": "1.63",
    "Earth": "",
    "Group": "1",
    "Electron Configuration": "[Kr] 5s1"
  },
  {
    "Number": "38",
    "Type": "alkaline earth metal",
    "Atomic Weight": "87.62",
    "Name": "Strontium",
    "Symbol": "Sr",
    "Melting Point": "769",
    "Boiling Point": "1384",
    "Density": "2.54",
    "Earth": "",
    "Group": "2",
    "Electron Configuration": "[Kr] 5s2"
  },
  {
    "Number": "39",
    "Type": "transition metal",
    "Atomic Weight": "88.906",
    "Name": "Yttrium",
    "Symbol": "Y",
    "Melting Point": "1523",
    "Boiling Point": "3337",
    "Density": "4.47",
    "Earth": "",
    "Group": "3",
    "Electron Configuration": "[Kr] 4d1 5s2"
  },
  {
    "Number": "40",
    "Type": "transition metal",
    "Atomic Weight": "91.224",
    "Name": "Zirconium",
    "Symbol": "Zr",
    "Melting Point": "1852",
    "Boiling Point": "4377",
    "Density": "6.51",
    "Earth": "0.03",
    "Group": "4",
    "Electron Configuration": "[Kr] 4d2 5s2"
  },
  {
    "Number": "41",
    "Type": "transition metal",
    "Atomic Weight": "92.906",
    "Name": "Niobium",
    "Symbol": "Nb",
    "Melting Point": "2468",
    "Boiling Point": "4927",
    "Density": "8.57",
    "Earth": "",
    "Group": "5",
    "Electron Configuration": "[Kr] 4d4 5s1"
  },
  {
    "Number": "42",
    "Type": "transition metal",
    "Atomic Weight": "95.94",
    "Name": "Molybdenum",
    "Symbol": "Mo",
    "Melting Point": "2617",
    "Boiling Point": "4612",
    "Density": "10.22",
    "Earth": "",
    "Group": "6",
    "Electron Configuration": "[Kr] 4d5 5s1"
  },
  {
    "Number": "43",
    "Type": "transition metal",
    "Atomic Weight": "98",
    "Name": "Technetium",
    "Symbol": "Tc",
    "Melting Point": "2200",
    "Boiling Point": "4877",
    "Density": "11.5",
    "Earth": "",
    "Group": "7",
    "Electron Configuration": "[Kr] 4d5 5s2"
  },
  {
    "Number": "44",
    "Type": "transition metal",
    "Atomic Weight": "101.07",
    "Name": "Ruthenium",
    "Symbol": "Ru",
    "Melting Point": "2250",
    "Boiling Point": "3900",
    "Density": "12.37",
    "Earth": "",
    "Group": "8",
    "Electron Configuration": "[Kr] 4d7 5s1"
  },
  {
    "Number": "45",
    "Type": "transition metal",
    "Atomic Weight": "102.906",
    "Name": "Rhodium",
    "Symbol": "Rh",
    "Melting Point": "1966",
    "Boiling Point": "3727",
    "Density": "12.41",
    "Earth": "",
    "Group": "9",
    "Electron Configuration": "[Kr] 4d8 5s1"
  },
  {
    "Number": "46",
    "Type": "transition metal",
    "Atomic Weight": "106.42",
    "Name": "Palladium",
    "Symbol": "Pd",
    "Melting Point": "1552",
    "Boiling Point": "2927",
    "Density": "12.02",
    "Earth": "",
    "Group": "10",
    "Electron Configuration": "[Kr] 4d10"
  },
  {
    "Number": "47",
    "Type": "transition metal",
    "Atomic Weight": "107.868",
    "Name": "Silver",
    "Symbol": "Ag",
    "Melting Point": "962",
    "Boiling Point": "2212",
    "Density": "10.5",
    "Earth": "",
    "Group": "11",
    "Electron Configuration": "[Kr] 4d10 5s1"
  },
  {
    "Number": "48",
    "Type": "transition metal",
    "Atomic Weight": "112.411",
    "Name": "Cadmium",
    "Symbol": "Cd",
    "Melting Point": "321",
    "Boiling Point": "765",
    "Density": "8.65",
    "Earth": "",
    "Group": "12",
    "Electron Configuration": "[Kr] 4d10 5s2"
  },
  {
    "Number": "49",
    "Type": "post transition metal",
    "Atomic Weight": "114.818",
    "Name": "Indium",
    "Symbol": "In",
    "Melting Point": "157",
    "Boiling Point": "2000",
    "Density": "7.31",
    "Earth": "",
    "Group": "13",
    "Electron Configuration": "[Kr] 4d10 5s2 5p1"
  },
  {
    "Number": "50",
    "Type": "post transition metal",
    "Atomic Weight": "118.71",
    "Name": "Tin",
    "Symbol": "Sn",
    "Melting Point": "232",
    "Boiling Point": "2270",
    "Density": "7.31",
    "Earth": "",
    "Group": "14",
    "Electron Configuration": "[Kr] 4d10 5s2 5p2"
  },
  {
    "Number": "51",
    "Type": "metalloid",
    "Atomic Weight": "121.76",
    "Name": "Antimony",
    "Symbol": "Sb",
    "Melting Point": "630",
    "Boiling Point": "1750",
    "Density": "6.68",
    "Earth": "",
    "Group": "15",
    "Electron Configuration": "[Kr] 4d10 5s2 5p3"
  },
  {
    "Number": "52",
    "Type": "metalloid",
    "Atomic Weight": "127.6",
    "Name": "Tellurium",
    "Symbol": "Te",
    "Melting Point": "449",
    "Boiling Point": "990",
    "Density": "6.24",
    "Earth": "",
    "Group": "16",
    "Electron Configuration": "[Kr] 4d10 5s2 5p4"
  },
  {
    "Number": "53",
    "Type": "halogen",
    "Atomic Weight": "126.905",
    "Name": "Iodine",
    "Symbol": "I",
    "Melting Point": "114",
    "Boiling Point": "184",
    "Density": "4.93",
    "Earth": "",
    "Group": "17",
    "Electron Configuration": "[Kr] 4d10 5s2 5p5"
  },
  {
    "Number": "54",
    "Type": "noble gas",
    "Atomic Weight": "131.293",
    "Name": "Xenon",
    "Symbol": "Xe",
    "Melting Point": "-112",
    "Boiling Point": "-108",
    "Density": "5.9",
    "Earth": "",
    "Group": "18",
    "Electron Configuration": "[Kr] 4d10 5s2 5p6"
  },
  {
    "Number": "55",
    "Type": "alkali metal",
    "Atomic Weight": "132.906",
    "Name": "Cesium",
    "Symbol": "Cs",
    "Melting Point": "29",
    "Boiling Point": "678",
    "Density": "1.87",
    "Earth": "",
    "Group": "1",
    "Electron Configuration": "[Xe] 6s1"
  },
  {
    "Number": "56",
    "Type": "alkaline earth metal",
    "Atomic Weight": "137.327",
    "Name": "Barium",
    "Symbol": "Ba",
    "Melting Point": "725",
    "Boiling Point": "1140",
    "Density": "3.59",
    "Earth": "0.05",
    "Group": "2",
    "Electron Configuration": "[Xe] 6s2"
  },
  {
    "Number": "57",
    "Type": "lanthanide",
    "Atomic Weight": "138.906",
    "Name": "Lanthanum",
    "Symbol": "La",
    "Melting Point": "920",
    "Boiling Point": "3469",
    "Density": "6.15",
    "Earth": "",
    "Group": "3",
    "Electron Configuration": "[Xe] 5d1 6s2"
  },
  {
    "Number": "58",
    "Type": "lanthanide",
    "Atomic Weight": "140.116",
    "Name": "Cerium",
    "Symbol": "Ce",
    "Melting Point": "795",
    "Boiling Point": "3257",
    "Density": "6.77",
    "Earth": "",
    "Group": "101",
    "Electron Configuration": "[Xe] 4f1 5d1 6s2"
  },
  {
    "Number": "59",
    "Type": "lanthanide",
    "Atomic Weight": "140.908",
    "Name": "Praseodymium",
    "Symbol": "Pr",
    "Melting Point": "935",
    "Boiling Point": "3127",
    "Density": "6.77",
    "Earth": "",
    "Group": "101",
    "Electron Configuration": "[Xe] 4f3 6s2"
  },
  {
    "Number": "60",
    "Type": "lanthanide",
    "Atomic Weight": "144.24",
    "Name": "Neodymium",
    "Symbol": "Nd",
    "Melting Point": "1010",
    "Boiling Point": "3127",
    "Density": "7.01",
    "Earth": "",
    "Group": "101",
    "Electron Configuration": "[Xe] 4f4 6s2"
  },
  {
    "Number": "61",
    "Type": "lanthanide",
    "Atomic Weight": "145",
    "Name": "Promethium",
    "Symbol": "Pm",
    "Melting Point": "1100",
    "Boiling Point": "3000",
    "Density": "7.3",
    "Earth": "",
    "Group": "101",
    "Electron Configuration": "[Xe] 4f5 6s2"
  },
  {
    "Number": "62",
    "Type": "lanthanide",
    "Atomic Weight": "150.36",
    "Name": "Samarium",
    "Symbol": "Sm",
    "Melting Point": "1072",
    "Boiling Point": "1900",
    "Density": "7.52",
    "Earth": "",
    "Group": "101",
    "Electron Configuration": "[Xe] 4f6 6s2"
  },
  {
    "Number": "63",
    "Type": "lanthanide",
    "Atomic Weight": "151.964",
    "Name": "Europium",
    "Symbol": "Eu",
    "Melting Point": "822",
    "Boiling Point": "1597",
    "Density": "5.24",
    "Earth": "",
    "Group": "101",
    "Electron Configuration": "[Xe] 4f7 6s2"
  },
  {
    "Number": "64",
    "Type": "lanthanide",
    "Atomic Weight": "157.25",
    "Name": "Gadolinium",
    "Symbol": "Gd",
    "Melting Point": "1311",
    "Boiling Point": "3233",
    "Density": "7.9",
    "Earth": "",
    "Group": "101",
    "Electron Configuration": "[Xe] 4f7 5d1 6s2"
  },
  {
    "Number": "65",
    "Type": "lanthanide",
    "Atomic Weight": "158.925",
    "Name": "Terbium",
    "Symbol": "Tb",
    "Melting Point": "1360",
    "Boiling Point": "3041",
    "Density": "8.23",
    "Earth": "",
    "Group": "101",
    "Electron Configuration": "[Xe] 4f9 6s2"
  },
  {
    "Number": "66",
    "Type": "lanthanide",
    "Atomic Weight": "162.5",
    "Name": "Dysprosium",
    "Symbol": "Dy",
    "Melting Point": "1412",
    "Boiling Point": "2562",
    "Density": "8.55",
    "Earth": "",
    "Group": "101",
    "Electron Configuration": "[Xe] 4f10 6s2"
  },
  {
    "Number": "67",
    "Type": "lanthanide",
    "Atomic Weight": "164.93",
    "Name": "Holmium",
    "Symbol": "Ho",
    "Melting Point": "1470",
    "Boiling Point": "2720",
    "Density": "8.8",
    "Earth": "",
    "Group": "101",
    "Electron Configuration": "[Xe] 4f11 6s2"
  },
  {
    "Number": "68",
    "Type": "lanthanide",
    "Atomic Weight": "167.259",
    "Name": "Erbium",
    "Symbol": "Er",
    "Melting Point": "1522",
    "Boiling Point": "2510",
    "Density": "9.07",
    "Earth": "",
    "Group": "101",
    "Electron Configuration": "[Xe] 4f12 6s2"
  },
  {
    "Number": "69",
    "Type": "lanthanide",
    "Atomic Weight": "168.934",
    "Name": "Thulium",
    "Symbol": "Tm",
    "Melting Point": "1545",
    "Boiling Point": "1727",
    "Density": "9.32",
    "Earth": "",
    "Group": "101",
    "Electron Configuration": "[Xe] 4f13 6s2"
  },
  {
    "Number": "70",
    "Type": "lanthanide",
    "Atomic Weight": "173.04",
    "Name": "Ytterbium",
    "Symbol": "Yb",
    "Melting Point": "824",
    "Boiling Point": "1466",
    "Density": "6.9",
    "Earth": "",
    "Group": "101",
    "Electron Configuration": "[Xe] 4f14 6s2"
  },
  {
    "Number": "71",
    "Type": "lanthanide",
    "Atomic Weight": "174.967",
    "Name": "Lutetium",
    "Symbol": "Lu",
    "Melting Point": "1656",
    "Boiling Point": "3315",
    "Density": "9.84",
    "Earth": "",
    "Group": "101",
    "Electron Configuration": "[Xe] 4f14 5d1 6s2"
  },
  {
    "Number": "72",
    "Type": "transition metal",
    "Atomic Weight": "178.49",
    "Name": "Hafnium",
    "Symbol": "Hf",
    "Melting Point": "2150",
    "Boiling Point": "5400",
    "Density": "13.31",
    "Earth": "",
    "Group": "4",
    "Electron Configuration": "[Xe] 4f14 5d2 6s2"
  },
  {
    "Number": "73",
    "Type": "transition metal",
    "Atomic Weight": "180.948",
    "Name": "Tantalum",
    "Symbol": "Ta",
    "Melting Point": "2996",
    "Boiling Point": "5425",
    "Density": "16.65",
    "Earth": "",
    "Group": "5",
    "Electron Configuration": "[Xe] 4f14 5d3 6s2"
  },
  {
    "Number": "74",
    "Type": "transition metal",
    "Atomic Weight": "183.84",
    "Name": "Tungsten",
    "Symbol": "W",
    "Melting Point": "3410",
    "Boiling Point": "5660",
    "Density": "19.35",
    "Earth": "",
    "Group": "6",
    "Electron Configuration": "[Xe] 4f14 5d4 6s2"
  },
  {
    "Number": "75",
    "Type": "transition metal",
    "Atomic Weight": "186.207",
    "Name": "Rhenium",
    "Symbol": "Re",
    "Melting Point": "3180",
    "Boiling Point": "5627",
    "Density": "21.04",
    "Earth": "",
    "Group": "7",
    "Electron Configuration": "[Xe] 4f14 5d5 6s2"
  },
  {
    "Number": "76",
    "Type": "transition metal",
    "Atomic Weight": "190.23",
    "Name": "Osmium",
    "Symbol": "Os",
    "Melting Point": "3045",
    "Boiling Point": "5027",
    "Density": "22.6",
    "Earth": "",
    "Group": "8",
    "Electron Configuration": "[Xe] 4f14 5d6 6s2"
  },
  {
    "Number": "77",
    "Type": "transition metal",
    "Atomic Weight": "192.217",
    "Name": "Iridium",
    "Symbol": "Ir",
    "Melting Point": "2410",
    "Boiling Point": "4527",
    "Density": "22.4",
    "Earth": "",
    "Group": "9",
    "Electron Configuration": "[Xe] 4f14 5d7 6s2"
  },
  {
    "Number": "78",
    "Type": "transition metal",
    "Atomic Weight": "195.078",
    "Name": "Platinum",
    "Symbol": "Pt",
    "Melting Point": "1772",
    "Boiling Point": "3827",
    "Density": "21.45",
    "Earth": "",
    "Group": "10",
    "Electron Configuration": "[Xe] 4f14 5d9 6s1"
  },
  {
    "Number": "79",
    "Type": "transition metal",
    "Atomic Weight": "196.967",
    "Name": "Gold",
    "Symbol": "Au",
    "Melting Point": "1064",
    "Boiling Point": "2807",
    "Density": "19.32",
    "Earth": "",
    "Group": "11",
    "Electron Configuration": "[Xe] 4f14 5d10 6s1"
  },
  {
    "Number": "80",
    "Type": "transition metal",
    "Atomic Weight": "200.59",
    "Name": "Mercury",
    "Symbol": "Hg",
    "Melting Point": "-39",
    "Boiling Point": "357",
    "Density": "13.55",
    "Earth": "",
    "Group": "12",
    "Electron Configuration": "[Xe] 4f14 5d10 6s2"
  },
  {
    "Number": "81",
    "Type": "post transition metal",
    "Atomic Weight": "204.383",
    "Name": "Thallium",
    "Symbol": "Tl",
    "Melting Point": "303",
    "Boiling Point": "1457",
    "Density": "11.85",
    "Earth": "",
    "Group": "13",
    "Electron Configuration": "[Xe] 4f14 5d10 6s2 6p1"
  },
  {
    "Number": "82",
    "Type": "post transition metal",
    "Atomic Weight": "207.2",
    "Name": "Lead",
    "Symbol": "Pb",
    "Melting Point": "327",
    "Boiling Point": "1740",
    "Density": "11.35",
    "Earth": "",
    "Group": "14",
    "Electron Configuration": "[Xe] 4f14 5d10 6s2 6p2"
  },
  {
    "Number": "83",
    "Type": "post transition metal",
    "Atomic Weight": "208.98",
    "Name": "Bismuth",
    "Symbol": "Bi",
    "Melting Point": "271",
    "Boiling Point": "1560",
    "Density": "9.75",
    "Earth": "",
    "Group": "15",
    "Electron Configuration": "[Xe] 4f14 5d10 6s2 6p3"
  },
  {
    "Number": "84",
    "Type": "metalloid",
    "Atomic Weight": "209",
    "Name": "Polonium",
    "Symbol": "Po",
    "Melting Point": "254",
    "Boiling Point": "962",
    "Density": "9.3",
    "Earth": "",
    "Group": "16",
    "Electron Configuration": "[Xe] 4f14 5d10 6s2 6p4"
  },
  {
    "Number": "85",
    "Type": "halogen",
    "Atomic Weight": "210",
    "Name": "Astatine",
    "Symbol": "At",
    "Melting Point": "302",
    "Boiling Point": "337",
    "Density": "0",
    "Earth": "",
    "Group": "17",
    "Electron Configuration": "[Xe] 4f14 5d10 6s2 6p5"
  },
  {
    "Number": "86",
    "Type": "noble gas",
    "Atomic Weight": "222",
    "Name": "Radon",
    "Symbol": "Rn",
    "Melting Point": "-71",
    "Boiling Point": "-62",
    "Density": "9.73",
    "Earth": "",
    "Group": "18",
    "Electron Configuration": "[Xe] 4f14 5d10 6s2 6p6"
  },
  {
    "Number": "87",
    "Type": "alkali metal",
    "Atomic Weight": "223",
    "Name": "Francium",
    "Symbol": "Fr",
    "Melting Point": "27",
    "Boiling Point": "677",
    "Density": "0",
    "Earth": "",
    "Group": "1",
    "Electron Configuration": "[Rn] 7s1"
  },
  {
    "Number": "88",
    "Type": "alkaline earth metal",
    "Atomic Weight": "226",
    "Name": "Radium",
    "Symbol": "Ra",
    "Melting Point": "700",
    "Boiling Point": "1737",
    "Density": "5.5",
    "Earth": "",
    "Group": "2",
    "Electron Configuration": "[Rn] 7s2"
  },
  {
    "Number": "89",
    "Type": "actinide",
    "Atomic Weight": "227",
    "Name": "Actinium",
    "Symbol": "Ac",
    "Melting Point": "1050",
    "Boiling Point": "3200",
    "Density": "10.07",
    "Earth": "",
    "Group": "3",
    "Electron Configuration": "[Rn] 6d1 7s2"
  },
  {
    "Number": "90",
    "Type": "actinide",
    "Atomic Weight": "232.038",
    "Name": "Thorium",
    "Symbol": "Th",
    "Melting Point": "1750",
    "Boiling Point": "4790",
    "Density": "11.72",
    "Earth": "",
    "Group": "102",
    "Electron Configuration": "[Rn] 6d2 7s2"
  },
  {
    "Number": "91",
    "Type": "actinide",
    "Atomic Weight": "231.036",
    "Name": "Protactinium",
    "Symbol": "Pa",
    "Melting Point": "1568",
    "Boiling Point": "0",
    "Density": "15.4",
    "Earth": "",
    "Group": "102",
    "Electron Configuration": "[Rn] 5f2 6d1 7s2"
  },
  {
    "Number": "92",
    "Type": "actinide",
    "Atomic Weight": "238.029",
    "Name": "Uranium",
    "Symbol": "U",
    "Melting Point": "1132",
    "Boiling Point": "3818",
    "Density": "18.95",
    "Earth": "",
    "Group": "102",
    "Electron Configuration": "[Rn] 5f3 6d1 7s2"
  },
  {
    "Number": "93",
    "Type": "actinide",
    "Atomic Weight": "237",
    "Name": "Neptunium",
    "Symbol": "Np",
    "Melting Point": "640",
    "Boiling Point": "3902",
    "Density": "20.2",
    "Earth": "",
    "Group": "102",
    "Electron Configuration": "[Rn] 5f4 6d1 7s2"
  },
  {
    "Number": "94",
    "Type": "actinide",
    "Atomic Weight": "244",
    "Name": "Plutonium",
    "Symbol": "Pu",
    "Melting Point": "640",
    "Boiling Point": "3235",
    "Density": "19.84",
    "Earth": "",
    "Group": "102",
    "Electron Configuration": "[Rn] 5f6 7s2"
  },
  {
    "Number": "95",
    "Type": "actinide",
    "Atomic Weight": "243",
    "Name": "Americium",
    "Symbol": "Am",
    "Melting Point": "994",
    "Boiling Point": "2607",
    "Density": "13.67",
    "Earth": "",
    "Group": "102",
    "Electron Configuration": "[Rn] 5f7 7s2"
  },
  {
    "Number": "96",
    "Type": "actinide",
    "Atomic Weight": "247",
    "Name": "Curium",
    "Symbol": "Cm",
    "Melting Point": "1340",
    "Boiling Point": "0",
    "Density": "13.5",
    "Earth": "",
    "Group": "102",
    "Electron Configuration": ""
  },
  {
    "Number": "97",
    "Type": "actinide",
    "Atomic Weight": "247",
    "Name": "Berkelium",
    "Symbol": "Bk",
    "Melting Point": "986",
    "Boiling Point": "0",
    "Density": "14.78",
    "Earth": "",
    "Group": "102",
    "Electron Configuration": ""
  },
  {
    "Number": "98",
    "Type": "actinide",
    "Atomic Weight": "251",
    "Name": "Californium",
    "Symbol": "Cf",
    "Melting Point": "900",
    "Boiling Point": "0",
    "Density": "15.1",
    "Earth": "",
    "Group": "102",
    "Electron Configuration": ""
  },
  {
    "Number": "99",
    "Type": "actinide",
    "Atomic Weight": "252",
    "Name": "Einsteinium",
    "Symbol": "Es",
    "Melting Point": "860",
    "Boiling Point": "0",
    "Density": "0",
    "Earth": "",
    "Group": "102",
    "Electron Configuration": ""
  },
  {
    "Number": "100",
    "Type": "actinide",
    "Atomic Weight": "257",
    "Name": "Fermium",
    "Symbol": "Fm",
    "Melting Point": "1527",
    "Boiling Point": "0",
    "Density": "0",
    "Earth": "",
    "Group": "102",
    "Electron Configuration": ""
  },
  {
    "Number": "101",
    "Type": "actinide",
    "Atomic Weight": "258",
    "Name": "Mendelevium",
    "Symbol": "Md",
    "Melting Point": "0",
    "Boiling Point": "0",
    "Density": "0",
    "Earth": "",
    "Group": "102",
    "Electron Configuration": ""
  },
  {
    "Number": "102",
    "Type": "actinide",
    "Atomic Weight": "259",
    "Name": "Nobelium",
    "Symbol": "No",
    "Melting Point": "827",
    "Boiling Point": "0",
    "Density": "0",
    "Earth": "",
    "Group": "102",
    "Electron Configuration": ""
  },
  {
    "Number": "103",
    "Type": "actinide",
    "Atomic Weight": "262",
    "Name": "Lawrencium",
    "Symbol": "Lr",
    "Melting Point": "1627",
    "Boiling Point": "0",
    "Density": "0",
    "Earth": "",
    "Group": "102",
    "Electron Configuration": ""
  },
  {
    "Number": "104",
    "Type": "transition metal",
    "Atomic Weight": "261",
    "Name": "Rutherfordium",
    "Symbol": "Rf",
    "Melting Point": "0",
    "Boiling Point": "0",
    "Density": "0",
    "Earth": "",
    "Group": "4",
    "Electron Configuration": ""
  },
  {
    "Number": "105",
    "Type": "transition metal",
    "Atomic Weight": "262",
    "Name": "Dubnium",
    "Symbol": "Db",
    "Melting Point": "0",
    "Boiling Point": "0",
    "Density": "0",
    "Earth": "",
    "Group": "5",
    "Electron Configuration": ""
  },
  {
    "Number": "106",
    "Type": "transition metal",
    "Atomic Weight": "266",
    "Name": "Seaborgium",
    "Symbol": "Sg",
    "Melting Point": "0",
    "Boiling Point": "0",
    "Density": "0",
    "Earth": "",
    "Group": "6",
    "Electron Configuration": ""
  },
  {
    "Number": "107",
    "Type": "transition metal",
    "Atomic Weight": "264",
    "Name": "Bohrium",
    "Symbol": "Bh",
    "Melting Point": "0",
    "Boiling Point": "0",
    "Density": "0",
    "Earth": "",
    "Group": "7",
    "Electron Configuration": ""
  },
  {
    "Number": "108",
    "Type": "transition metal",
    "Atomic Weight": "277",
    "Name": "Hassium",
    "Symbol": "Hs",
    "Melting Point": "0",
    "Boiling Point": "0",
    "Density": "0",
    "Earth": "",
    "Group": "8",
    "Electron Configuration": ""
  },
  {
    "Number": "109",
    "Type": "transition metal",
    "Atomic Weight": "268",
    "Name": "Meitnerium",
    "Symbol": "Mt",
    "Melting Point": "0",
    "Boiling Point": "0",
    "Density": "0",
    "Earth": "",
    "Group": "9",
    "Electron Configuration": ""
  }
]