apiVersion: v1
# at the time of writing the app lives here:
kind: Service
metadata:
  name: b18-csv-generator
spec:
  ports:
    - name: web-http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: b18-csv-generator
  type: LoadBalancer
  externalTrafficPolicy: Cluster

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: b18-csv-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: b18-csv-generator
  template:
    metadata:
      labels:
        app: b18-csv-generator
    spec:
      containers:
        - name: b18-csv-generator
          image: gcr.io/diamond-privreg/b18-csv-generator:0.1.0
          env:
            - name: NEXT_PUBLIC_API_HOST # not used
              value: "b18-csv-generator.xma12127.svc.cluster.local:3001"
          resources:
            limits:
              cpu: "1"
              memory: 300M
          ports:
            - name: web-http
              containerPort: 8080
              